#!/bin/bash

source crud/script

function default_main() {
    display_main_menu
    read -p "$(center_text "Enter your choice: ")" choice
    case $choice in
        1) take_quiz ;;
        2) create_quiz ;;
        3) edit_quiz ;;
        4) delete_quiz ;;
        *) echo "Invalid choice" ;;
    esac
}