#!/bin/bash

source cli/default

function init_db() {
    [ ! -e "database.json" ] && echo '{"quizzes:" []}' > database.json
}

function help() {
    echo "Usage: $0 [OPTION]"
    echo
    echo "Options:"
    echo "  --default  Run quizcript with default command line interface"
    echo "  --dialog   Run quizcript with dialog interface"
    echo "  --help     Display this help message"
}

function main() {
    init_db

    case $1 in
        "") default_menu ;;
        "--default") default_menu ;;
        "--help") help ;;
        *) help ;;
    esac
}

main $@